In [3]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('data/stop_times.txt', header=None)
df

C:\Users\tamas\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,0,1,2,3,4,5,6,7,8
0,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
1,B0571610,F04181,08:03:00,08:03:00,0,NaN,NaN,NaN,0.0
2,B0571610,F04526,08:06:00,08:06:00,1,NaN,NaN,NaN,160.0
3,B0571611,F04526,08:30:00,08:30:00,0,NaN,NaN,NaN,0.0
4,B0571611,F04181,08:33:00,08:33:00,1,NaN,NaN,NaN,160.0
5,B0571612,F04181,08:33:00,08:33:00,0,NaN,NaN,NaN,0.0
6,B0571612,F04526,08:36:00,08:36:00,1,NaN,NaN,NaN,160.0
7,B0571613,F04526,09:00:00,09:00:00,0,NaN,NaN,NaN,0.0
8,B0571613,F04181,09:03:00,09:03:00,1,NaN,NaN,NaN,160.0
9,B0571614,F04181,09:03:00,09:03:00,0,NaN,NaN,NaN,0.0
10,B0571614,F04526,09:06:00,09:06:00,1,NaN,NaN,NaN,160.0
11,B0571615,F04526,09:30:00,09:30:00,0,NaN,NaN,NaN,0.0
12,B0571615,F04181,09:33:00,09:33:00,1,NaN,NaN,NaN,160.0
13,B0571616,F04181,09:33:00,09:33:00,0,NaN,NaN,NaN,0.0
14,B0571616,F04526,09:36:00,09:36:00,1,NaN,NaN,NaN,160.0
15,B0571617,F04526,10:00:00,10:00:00,0,NaN,NaN,NaN,0.0
16,B0571617,F04181,10:03:00,10:03:00,1,NaN,NaN,NaN,160.0
17,B0571618,F04181,10:03:00,10:03:00,0,NaN,NaN,NaN,0.0
18,B0571618,F04526,10:06:00,10:06:00,1,NaN,NaN,NaN,160.0
19,B0571619,F04526,10:30:00,10:30:00,0,NaN,NaN,NaN,0.0
20,B0571619,F04181,10:33:00,10:33:00,1,NaN,NaN,NaN,160.0
21,B0571620,F04181,10:33:00,10:33:00,0,NaN,NaN,NaN,0.0
22,B0571620,F04526,10:36:00,10:36:00,1,NaN,NaN,NaN,160.0
23,B0571621,F04526,11:00:00,11:00:00,0,NaN,NaN,NaN,0.0
24,B0571621,F04181,11:03:00,11:03:00,1,NaN,NaN,NaN,160.0
25,B0571622,F04181,11:03:00,11:03:00,0,NaN,NaN,NaN,0.0
26,B0571622,F04526,11:06:00,11:06:00,1,NaN,NaN,NaN,160.0
27,B0571623,F04526,11:30:00,11:30:00,0,NaN,NaN,NaN,0.0
28,B0571623,F04181,11:33:00,11:33:00,1,NaN,NaN,NaN,160.0
29,B0571624,F04181,11:33:00,11:33:00,0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...
3996834,B8953497,066460,06:01:00,06:01:00,28,NaN,NaN,NaN,16582
3996835,B8953498,066460,06:13:00,06:13:00,0,NaN,NaN,NaN,0
3996836,B8953498,066458,06:14:00,06:14:00,1,NaN,NaN,NaN,528
3996837,B8953498,066456,06:16:00,06:16:00,2,NaN,NaN,NaN,1039
3996838,B8953498,066454,06:17:00,06:17:00,3,NaN,NaN,NaN,1671
3996839,B8953498,066452,06:18:00,06:18:00,4,NaN,NaN,NaN,2139
3996840,B8953498,008265,06:20:00,06:20:00,5,NaN,NaN,NaN,3123
3996841,B8953498,008153,06:23:00,06:23:00,6,NaN,NaN,NaN,3981
3996842,B8953498,F01502,06:25:00,06:25:00,7,NaN,NaN,NaN,4355
3996843,B8953498,F01499,06:27:00,06:27:00,8,NaN,NaN,NaN,4945
3996844,B8953498,008286,06:29:00,06:29:00,9,NaN,NaN,NaN,5413
3996845,B8953498,008147,06:30:00,06:30:00,10,NaN,NaN,NaN,6109
3996846,B8953498,008149,06:32:00,06:32:00,11,NaN,NaN,NaN,6690
3996847,B8953498,F01275,06:34:00,06:34:00,12,NaN,NaN,NaN,7258
3996848,B8953498,F01328,06:36:00,06:36:00,13,NaN,NaN,NaN,7829
3996849,B8953498,F01323,06:38:00,06:38:00,14,NaN,NaN,NaN,8361
3996850,B8953498,F02743,06:40:00,06:40:00,15,NaN,NaN,NaN,9127
3996851,B8953498,F02732,06:42:00,06:42:00,16,NaN,NaN,NaN,9725
3996852,B8953498,F02980,06:44:00,06:44:00,17,NaN,NaN,NaN,10108
3996853,B8953498,F02924,06:46:00,06:46:00,18,NaN,NaN,NaN,10585
3996854,B8953498,F02893,06:47:00,06:47:00,19,NaN,NaN,NaN,10946
3996855,B8953498,F02631,06:48:00,06:48:00,20,NaN,NaN,NaN,11695
3996856,B8953498,F02597,06:50:00,06:50:00,21,NaN,NaN,NaN,12121
3996857,B8953498,F02642,06:51:00,06:51:00,22,NaN,NaN,NaN,12823
3996858,B8953498,F02578,06:53:00,06:53:00,23,NaN,NaN,NaN,13122
3996859,B8953498,F02527,06:54:00,06:54:00,24,NaN,NaN,NaN,13924
3996860,B8953498,F00626,06:56:00,06:56:00,25,NaN,NaN,NaN,15023
3996861,B8953498,F00614,06:58:00,06:58:00,26,NaN,NaN,NaN,15487
3996862,B8953498,F00586,06:59:00,06:59:00,27,NaN,NaN,NaN,16189
3996863,B8953498,F00569,07:01:00,07:01:00,28,NaN,NaN,NaN,16635

In [33]:
filter_mask = df[2] < '08:06:00' #ez elotti
filter_mask2 = df[2] != df[3] #arrival nem = departure
filtered_df = df[filter_mask]
filtered_df2 = filtered_df[filter_mask2]
filtered_df2

C:\Users\tamas\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

,0,1,2,3,4,5,6,7,8
33596,B5018418,061280,05:23:00,05:24:00,26,NaN,NaN,NaN,10846.0
34273,B5018428,061280,05:53:00,05:54:00,26,NaN,NaN,NaN,10846.0
34312,B501843,061280,04:33:00,04:34:00,26,NaN,NaN,NaN,10846.0
34337,B5018431,061222,05:15:00,05:17:00,12,NaN,NaN,NaN,5676.0
34390,B5018433,061280,06:23:00,06:24:00,26,NaN,NaN,NaN,10846.0
34415,B5018436,061222,05:45:00,05:47:00,12,NaN,NaN,NaN,5676.0
34468,B5018438,061280,06:58:00,06:59:00,26,NaN,NaN,NaN,10846.0
34493,B5018441,061222,06:15:00,06:17:00,12,NaN,NaN,NaN,5676.0
34546,B5018443,061280,07:28:00,07:29:00,26,NaN,NaN,NaN,10846.0
34571,B5018446,061222,06:45:00,06:47:00,12,NaN,NaN,NaN,5676.0
34624,B5018448,061280,07:58:00,07:59:00,26,NaN,NaN,NaN,10846.0
34649,B5018451,061222,07:09:00,07:11:00,12,NaN,NaN,NaN,5676.0
34727,B5018456,061222,07:39:00,07:41:00,12,NaN,NaN,NaN,5676.0
35131,B501848,061280,04:53:00,04:54:00,26,NaN,NaN,NaN,10846.0
36744,B5018618,061280,05:23:00,05:24:00,26,Újbuda-központ M,NaN,NaN,10846.0
37343,B5018628,061280,05:53:00,05:54:00,26,Újbuda-központ M,NaN,NaN,10846.0
37382,B501863,061280,04:33:00,04:34:00,26,Újbuda-központ M,NaN,NaN,10846.0
37407,B5018631,061222,05:15:00,05:17:00,12,Budatétény vá. (Campona),NaN,NaN,5676.0
37460,B5018633,061280,06:23:00,06:24:00,26,Újbuda-központ M,NaN,NaN,10846.0
37485,B5018636,061222,05:45:00,05:47:00,12,Budatétény vá. (Campona),NaN,NaN,5676.0
37538,B5018638,061280,06:53:00,06:54:00,26,Újbuda-központ M,NaN,NaN,10846.0
37563,B5018641,061222,06:15:00,06:17:00,12,Budatétény vá. (Campona),NaN,NaN,5676.0
37616,B5018643,061280,07:23:00,07:24:00,26,Újbuda-központ M,NaN,NaN,10846.0
37641,B5018646,061222,06:45:00,06:47:00,12,Budatétény vá. (Campona),NaN,NaN,5676.0
37694,B5018648,061280,07:53:00,07:54:00,26,Újbuda-központ M,NaN,NaN,10846.0
37719,B5018651,061222,07:15:00,07:17:00,12,Budatétény vá. (Campona),NaN,NaN,5676.0
37797,B5018656,061222,07:45:00,07:47:00,12,Budatétény vá. (Campona),NaN,NaN,5676.0
38201,B501868,061280,04:53:00,04:54:00,26,Újbuda-központ M,NaN,NaN,10846.0
85150,B62047354,F02292,07:57:00,07:58:00,7,NaN,NaN,NaN,2686
94661,B65444296,F03258,07:36:00,07:37:00,13,NaN,NaN,NaN,6277
...,...,...,...,...,...,...,...,...,...
3870548,B892697673,F02197,05:05:00,05:06:00,11,NaN,NaN,NaN,4299
3870559,B892697673,036678,05:19:00,05:21:00,22,NaN,NaN,NaN,8465
3870595,B892697679,036678,06:26:00,06:28:00,22,NaN,NaN,NaN,8465
3870598,B892697679,069090,06:33:00,06:34:00,25,NaN,NaN,NaN,9867
3883114,B89425106,011723,07:18:00,07:21:00,6,NaN,NaN,NaN,10741
3883712,B894251323,011723,05:38:00,05:42:00,6,NaN,NaN,NaN,10741
3883732,B894251324,011723,06:38:00,06:42:00,6,NaN,NaN,NaN,10741
3884167,B8942536,011723,05:17:00,05:22:00,6,NaN,NaN,NaN,10741
3884331,B894254,011725,04:15:00,04:16:00,10,NaN,NaN,NaN,5048
3885541,B8942578,011723,06:18:00,06:22:00,6,NaN,NaN,NaN,10741
3887921,B8943121,F03604,05:19:00,05:22:00,19,NaN,NaN,NaN,11798
3888188,B8943131,F03604,05:40:00,05:42:00,19,NaN,NaN,NaN,11798
3888370,B8943136,F03604,06:00:00,06:02:00,19,NaN,NaN,NaN,11798
3888552,B8943141,F03604,06:20:00,06:22:00,19,NaN,NaN,NaN,11798
3888838,B8943146,F03604,06:41:00,06:42:00,19,NaN,NaN,NaN,11798
3888968,B8943151,F03604,07:01:00,07:02:00,19,NaN,NaN,NaN,11798
3888994,B8943156,F03604,07:21:00,07:22:00,19,NaN,NaN,NaN,11798
3889027,B8943166,F03604,07:47:00,07:55:00,19,NaN,NaN,NaN,11798
3966511,B895064,F00804,05:01:00,05:02:00,21,NaN,NaN,NaN,9489
3978417,B89514108,011723,06:02:00,06:06:00,11,NaN,NaN,NaN,10837
3978457,B89514113,011723,06:14:00,06:15:00,11,NaN,NaN,NaN,10837
3978595,B89514162,011723,06:40:00,06:44:00,11,NaN,NaN,NaN,10837
3978635,B89514167,011723,06:52:00,06:54:00,11,NaN,NaN,NaN,10837
3978723,B89514177,011723,07:12:00,07:13:00,11,NaN,NaN,NaN,10837
3978763,B89514182,011723,07:22:00,07:23:00,11,NaN,NaN,NaN,10837
3978803,B89514187,011723,07:34:00,07:35:00,11,NaN,NaN,NaN,10837
3978864,B89514192,011723,07:44:00,07:45:00,11,NaN,NaN,NaN,10837
3978904,B89514197,011723,07:56:00,07:57:00,11,NaN,NaN,NaN,10837
3979762,B8951440,011723,05:10:00,05:15:00,11,NaN,NaN,NaN,10837
3981561,B8951468,011723,05:36:00,05:37:00,11,NaN,NaN,NaN,10837